routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/category/ads/{slug}', 'HomeController@categoryAdds')->name('category_adds');
Route::get('/tag/ads/{name}', 'HomeController@tagAdds')->name('tag_adds');
Route::get('/user/ads/{id}', 'HomeController@userAdds')->name('user_adds');
Route::get('/condition/ads', 'HomeController@conditionAdds')->name('condition_adds');
Route::get('/price/range/ads', 'HomeController@priceRangeAdds')->name('price_range_adds');
Route::get('/search/ads', 'HomeController@searchAdds')->name('post_search');
Route::get('/help/support', 'HomeController@Support')->name('help_support');
Route::get('/about', 'HomeController@About')->name('about');

Route::prefix('users')->name('user.')->group(function(){
    Route::get('/userad','UserDetailsController@userAdd')->name('userdetails.useradd');
    Route::get('/save/favorite/{postid}','UserDetailsController@saveAsFavorite')->name('userdetails.save_as_favorite');
    Route::get('/favorite/ad','UserDetailsController@userFavorite')->name('userdetails.favoriteadd');
    Route::put('/change/password','UserDetailsController@changePassword')->name('userdetails.change_password');
    Route::get('/remove/favorite/{postid}','UserDetailsController@removeFavorite')->name('userdetails.removefavorite');

    Route::resource('/userdetails','UserDetailsController');


    Route::get('/ad/sold/{postid}','AddPostController@adSold')->name('userdetails.ad_sold');
    Route::resource('/addpost','AddPostController');

});




Route::namespace('Admin')->prefix('admin')->name('admin.')->group(function() {
    Route::resource('/roles','AdminRoleController',['except' => ['show']]);
    Route::resource('/users','AdminUserController',['except' => ['show']]);
    Route::resource('/categories','AdminCategoryController');
    Route::get('/category/ads/{id}','AdminCategoryController@categoryAd')->name('category.ads');

    Route::get('/dashboard','AdminController@index')->name('admin.dashboard');
    Route::get('/ad/featured/toggle/{id}','AdminController@featuredToggle')->name('admin.featured_toggle');
    Route::get('/ad/status/toggle/{id}','AdminController@statusToggle')->name('admin.status_toggle');
    Route::get('/admin/profile','AdminController@adminProfile')->name('admin.profile');
    Route::put('/admin/update/profile','AdminController@adminUpdateProfile')->name('admin.update.profile');
    Route::put('/admin/change/password','AdminController@adminChangePassword')->name('admin.change_password');
    Route::get('/all/adds','AdminController@allAds')->name('admin.all_ads');

});

app/Role.php
<?php

namespace App;

use App\User;
use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    protected $fillable = ['name',];

    public function users(){
        return $this->belongsToMany(User::class);
    }
}

resources/views/admin/roles/create.blade.php
@extends('layouts.admin_app')

@section('content')
    <div class="row">
        <div class="col-md-8 mx-auto">
            <div class="card">
                <div class="card-header bg-primary text-white text-center">
                    Add Role
                </div>
                <div class="card-body">
                    <form action="{{ route('admin.roles.store') }}" method="POST">
                        @csrf

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">Role Name</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}" autofocus>

                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-8 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                   Add
                                </button>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/roles/edit.blade.php
@extends('layouts.admin_app')

@section('content')
    <div class="row">
        <div class="col-md-8 mx-auto">
            <div class="card">
                <div class="card-header bg-primary text-white text-center">
                    Edit Role {{$role->name}}
                </div>
                <div class="card-body">
                    <form action="{{ route('admin.roles.update',$role->id) }}" method="POST">
                        {{ method_field('PUT') }}
                        @csrf

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">Role Name</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{$role->name}}" autofocus>

                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-8 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                   Update
                                </button>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/roles/index.blade.php
@extends('layouts.admin_app')

@section('content')
    <div class="row">
        <div class="col-md-8 mx-auto">
            <div class="card">
                <div class="card-header bg-primary text-white text-center">
                    All Roles
                </div>
                <div class="card-body">
                    <table class="table table-bordered table-inverse table-hover">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Role Name</th>
                                <th>Edit</th>
                                <th>Delete</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($roles as $role)
                                <tr>
                                    <td>{{$role->id}}</td>
                                    <td>{{$role->name}}</td>
                                    <td>
                                        <a href="{{ route('admin.roles.edit',$role->id) }}" class="btn btn-sm btn-success">
                                            <i class="fa fa-edit"></i>
                                        </a>
                                    </td>
                                    <td>
                                    <form
                                    class="d-inline"
                                    action="{{ route('admin.roles.destroy',$role) }}"
                                    method="POST">
                                        @csrf
                                        {{ method_field('DELETE') }}

                                        <button class="btn btn-danger btn-sm">
                                            <i class="fa fa-trash"></i>
                                        </button>
                                    </form>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    </div>
@endsection