routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/category/ads/{slug}', 'HomeController@categoryAdds')->name('category_adds');
Route::get('/tag/ads/{name}', 'HomeController@tagAdds')->name('tag_adds');
Route::get('/user/ads/{id}', 'HomeController@userAdds')->name('user_adds');
Route::get('/condition/ads', 'HomeController@conditionAdds')->name('condition_adds');
Route::get('/price/range/ads', 'HomeController@priceRangeAdds')->name('price_range_adds');
Route::get('/search/ads', 'HomeController@searchAdds')->name('post_search');
Route::get('/help/support', 'HomeController@Support')->name('help_support');
Route::get('/about', 'HomeController@About')->name('about');

Route::prefix('users')->name('user.')->group(function(){
    Route::get('/userad','UserDetailsController@userAdd')->name('userdetails.useradd');
    Route::get('/save/favorite/{postid}','UserDetailsController@saveAsFavorite')->name('userdetails.save_as_favorite');
    Route::get('/favorite/ad','UserDetailsController@userFavorite')->name('userdetails.favoriteadd');
    Route::put('/change/password','UserDetailsController@changePassword')->name('userdetails.change_password');
    Route::get('/remove/favorite/{postid}','UserDetailsController@removeFavorite')->name('userdetails.removefavorite');

    Route::resource('/userdetails','UserDetailsController');


    Route::get('/ad/sold/{postid}','AddPostController@adSold')->name('userdetails.ad_sold');
    Route::resource('/addpost','AddPostController');

});




Route::namespace('Admin')->prefix('admin')->name('admin.')->group(function() {
    Route::resource('/roles','AdminRoleController',['except' => ['show']]);
    Route::resource('/users','AdminUserController',['except' => ['show']]);
    Route::resource('/categories','AdminCategoryController');
    Route::get('/category/ads/{id}','AdminCategoryController@categoryAd')->name('category.ads');

    Route::get('/dashboard','AdminController@index')->name('admin.dashboard');
    Route::get('/ad/featured/toggle/{id}','AdminController@featuredToggle')->name('admin.featured_toggle');
    Route::get('/ad/status/toggle/{id}','AdminController@statusToggle')->name('admin.status_toggle');
    Route::get('/admin/profile','AdminController@adminProfile')->name('admin.profile');
    Route::put('/admin/update/profile','AdminController@adminUpdateProfile')->name('admin.update.profile');
    Route::put('/admin/change/password','AdminController@adminChangePassword')->name('admin.change_password');
    Route::get('/all/adds','AdminController@allAds')->name('admin.all_ads');

});

app/User.php
<?php

namespace App;

use App\AddPost;
use App\AddPostLike;
use App\Role;
use Creativeorange\Gravatar\Facades\Gravatar;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','phone_number',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function roles(){
        return $this->belongsToMany(Role::class);
    }

    public function adds(){
        return $this->hasMany(AddPost::class);
    }

    public function favorites(){
        return $this->belongsToMany('App\AddPost', 'add_post_likes','user_id','add_post_id');
    }

    public function gravatar(){
        return Gravatar::get('email@example.com');
    }


    public function hasAnyRoles($roles){
        if($this->roles()->whereIn('name',$roles)->first()){
            return true;
        }
        return false;
    }

    public function hasRole($role){
        if($this->roles()->where('name',$role)->first()){
            return true;
        }

        return false;
    }


}

resources/views/admin/users/create.blade.php
@extends('layouts.admin_app')

@section('content')

    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header bg-primary text-white text-center">Add Admin</div>

                <div class="card-body">

                    <form action="{{ route('admin.users.store') }}" method="POST" novalidate>
                        @csrf
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}" required autocomplete="name" autofocus>

                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" required autocomplete="email">

                                @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="password" required autocomplete="new-password">

                                @error('password')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password-confirm" class="col-md-4 col-form-label text-md-right">{{ __('Confirm Password') }}</label>

                            <div class="col-md-6">
                                <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required autocomplete="new-password">
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="roles" class="col-md-4 col-form-label text-md-right">{{ __('Roles') }}</label>
                            <div class="col-md-6">
                                @foreach ($roles as $role)
                                <div class="form-check">
                                    <input  type="checkbox" name="roles[]" value={{$role->id}}
                                    >
                                    <label>{{$role->name}}</label>
                                </div>
                                @endforeach

                                @error('roles')
                                    <span class="invalid-feedback d-block" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>


                        </div>

                       <div class="form-gorup row">
                            <div class="mx-auto">
                                <input type="submit" value="Add Admin" class="btn btn-primary btn-sm">
                            </div>
                       </div>
                    </form>

                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/admin/users/edit.blade.php
@extends('layouts.admin_app')

@section('content')

    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Edit User {{$user->name}}</div>

                <div class="card-body">

                    <form action="{{ route('admin.users.update',$user) }}" method="POST">
                        @csrf
                        {{ method_field('PUT') }}

                        <div class="form-group row">
                            <label for="name" class="col-md-2 col-form-label text-md-right">name</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ $user->name }}" required autofocus>

                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="email" class="col-md-2 col-form-label text-md-right">Email</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ $user->email }}" required autocomplete="email" autofocus>

                                @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                             <label for="role" class="col-md-2 col-form-label text-md-right">Roles</label>
                            <div class="col-md-6">
                                @foreach ($roles as $role)
                                <div class="form-check">
                                    <input type="checkbox" name="roles[]" value={{$role->id}}
                                        @if ($user->roles->pluck('id')->contains($role->id))
                                            checked
                                        @endif
                                    >
                                    <label>{{$role->name}}</label>
                                </div>
                                @endforeach
                            </div>
                        </div>

                        <input type="submit" value="Update" class="btn btn-primary btn-sm">
                    </form>

                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/admin/users/index.blade.php
@extends('layouts.admin_app')

@section('content')

    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Users</div>

                <div class="card-body">
                    <table class="table table-bordered table-inverse table-hover">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Name</th>
                                <th>Email</th>
                                <th>Roles</th>
                                <th>Actions</th>
                            </tr>
                        </thead>


                    <tbody>
                        @foreach ($users as $user)
                        <tr>
                            <td>{{$user->id}}</td>
                            <td>{{$user->name}}</td>

                            <td>{{$user->email}}</td>
                            <td>{{implode(',',$user->roles()->get()->pluck('name')->toArray())}}</td>
                            <td>

                                   <a href="{{ route('admin.users.edit',$user->id) }}" class="btn btn-sm btn-success">Edit</a>




                                    <form
                                    class="d-inline"
                                    action="{{ route('admin.users.destroy',$user) }}"
                                    method="POST">
                                        @csrf
                                        {{ method_field('DELETE') }}

                                        <button class="btn btn-danger btn-sm">Delete</button>
                                    </form>




                            </td>
                        </tr>
                         @endforeach
                    </tbody>

                   </table>

                </div>
            </div>
        </div>
    </div>

@endsection