routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/category/ads/{slug}', 'HomeController@categoryAdds')->name('category_adds');
Route::get('/tag/ads/{name}', 'HomeController@tagAdds')->name('tag_adds');
Route::get('/user/ads/{id}', 'HomeController@userAdds')->name('user_adds');
Route::get('/condition/ads', 'HomeController@conditionAdds')->name('condition_adds');
Route::get('/price/range/ads', 'HomeController@priceRangeAdds')->name('price_range_adds');
Route::get('/search/ads', 'HomeController@searchAdds')->name('post_search');
Route::get('/help/support', 'HomeController@Support')->name('help_support');
Route::get('/about', 'HomeController@About')->name('about');

Route::prefix('users')->name('user.')->group(function(){
    Route::get('/userad','UserDetailsController@userAdd')->name('userdetails.useradd');
    Route::get('/save/favorite/{postid}','UserDetailsController@saveAsFavorite')->name('userdetails.save_as_favorite');
    Route::get('/favorite/ad','UserDetailsController@userFavorite')->name('userdetails.favoriteadd');
    Route::put('/change/password','UserDetailsController@changePassword')->name('userdetails.change_password');
    Route::get('/remove/favorite/{postid}','UserDetailsController@removeFavorite')->name('userdetails.removefavorite');

    Route::resource('/userdetails','UserDetailsController');


    Route::get('/ad/sold/{postid}','AddPostController@adSold')->name('userdetails.ad_sold');
    Route::resource('/addpost','AddPostController');

});




Route::namespace('Admin')->prefix('admin')->name('admin.')->group(function() {
    Route::resource('/roles','AdminRoleController',['except' => ['show']]);
    Route::resource('/users','AdminUserController',['except' => ['show']]);
    Route::resource('/categories','AdminCategoryController');
    Route::get('/category/ads/{id}','AdminCategoryController@categoryAd')->name('category.ads');

    Route::get('/dashboard','AdminController@index')->name('admin.dashboard');
    Route::get('/ad/featured/toggle/{id}','AdminController@featuredToggle')->name('admin.featured_toggle');
    Route::get('/ad/status/toggle/{id}','AdminController@statusToggle')->name('admin.status_toggle');
    Route::get('/admin/profile','AdminController@adminProfile')->name('admin.profile');
    Route::put('/admin/update/profile','AdminController@adminUpdateProfile')->name('admin.update.profile');
    Route::put('/admin/change/password','AdminController@adminChangePassword')->name('admin.change_password');
    Route::get('/all/adds','AdminController@allAds')->name('admin.all_ads');

});

app/Category.php
<?php

namespace App;

use App\AddPost;
use App\Category;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Category extends Model
{
    protected $fillable = ['name','image'];

    public function addposts(){
        return $this->hasMany(AddPost::class);
    }

    public static function boot()
    {
        parent::boot();

        static::saving(function ($model) {
            $model->slug = Str::slug($model->name, '-');
        });
    }
}

resources/views/admin/categories/category_ads.blade.php
@extends('layouts.admin_app')

@section('content')

    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header bg-primary text-white text-center">
                   {{$category->name}}'s Ads
                </div>
                <div class="card-body">

                    <table class="table table-sm table-inverse table-hover">
                        <thead>
                            <tr>
                                <th>Owner</th>
                                <th>Title</th>
                                <th>Price</th>
                                <th>Area</th>
                                <th>Location</th>
                                <th>Codition</th>
                                <th>Type</th>
                                <th>Status</th>
                                <th>Active</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($category_ads as $ad)
                            <tr>
                                <td>{{$ad->user->name}}</td>
                                <td>{{$ad->title}}</td>
                                <td>{{$ad->price}}</td>
                                <td>{{$ad->area}}</td>
                                <td>{{$ad->division}}--{{$ad->area}}</td>
                                <td>{{$ad->condition}}</td>
                                <td>{{$ad->type}}</td>
                                 <td>
                                    @if ($ad->sold)
                                       Sold
                                    @else
                                        Not Sold
                                    @endif
                                </td>
                                <td>
                                    @if ($ad->active)
                                        <a href="{{ route('admin.admin.status_toggle',$ad->id) }}" class="btn btn-sm btn-info">Make Inactive</a>
                                    @else
                                        <a href="{{ route('admin.admin.status_toggle',$ad->id) }}" class="btn btn-sm btn-success">Make Active</a>
                                    @endif
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                    {{$category_ads->links()}}
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/admin/categories/index.blade.php
@extends('layouts.admin_app')

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-6">
                    <div class="card">
                        <div class="card-header bg-primary text-white text-center">
                           All Categories
                        </div>
                        <div class="card-body">
                            <table class="table table-bordered table-inverse table-hover">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Category Name</th>
                                        <th>Slug Name</th>
                                        <th>Category Image</th>
                                        <th>Category Posts</th>
                                        <th>Edit</th>
                                        <th>Delete</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($categories as $category)
                                        <tr>
                                            <td>{{$category->id}}</td>
                                            <td>{{$category->name}}</td>
                                            <td>{{$category->slug}}</td>
                                            <td>
                                            @if ($category->image)
                                                <img src="/storage/category_photos/{{$category->image}}" alt="" width="20px">
                                            @else
                                                <img src="/storage/category_photos/default.png" alt="" width="20px">
                                            @endif
                                            </td>
                                            <td>
                                                <a href="{{ route('admin.category.ads',$category->id) }}" class="btn btn-sm btn-info">
                                                    View
                                                </a>
                                            </td>
                                            <td>
                                                <a href="{{ route('admin.categories.edit',$category->id) }}" class="btn btn-sm btn-success">
                                                    Edit
                                                </a>
                                            </td>
                                            <td>
                                            <form
                                            class="d-inline"
                                            action="{{ route('admin.categories.destroy',$category) }}"
                                            method="POST">
                                                @csrf
                                                {{ method_field('DELETE') }}

                                                <button class="btn btn-danger btn-sm">
                                                   Delete
                                                </button>
                                            </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>

                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="card">
                <div class="card-header bg-primary text-white text-center">
                    Add Category
                </div>
                <div class="card-body">
                    <form action="{{ $action }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        @isset ($edit_category)
                            {{method_field('PUT')}}
                        @endisset


                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">Category Name</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{old('name',$edit_category->name ?? null)}}" autofocus>

                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="image" class="col-md-4 col-form-label text-md-right">Category Image</label>

                            <div class="col-md-6">
                                <input id="image" type="file" class="form-control"  name="image">

                                @error('image')
                                    <span class="invalid-feedback d-block" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        @isset($edit_category)
                            <div class="form-group row">
                                <div class="col-md-12 text-center">
                                    <img src="/storage/category_photos/{{$edit_category->image}}" alt="" class="img-fluid" width="100px">
                                </div>
                            </div>
                        @endisset


                        <div class="form-group row mb-0">
                            <div class="col-md-8 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                   @if (isset($edit_category))
                                       Edit
                                    @else
                                     Add
                                   @endif
                                </button>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
                </div>
            </div>
        </div>
    </div>
@endsection