routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/category/ads/{slug}', 'HomeController@categoryAdds')->name('category_adds');
Route::get('/tag/ads/{name}', 'HomeController@tagAdds')->name('tag_adds');
Route::get('/user/ads/{id}', 'HomeController@userAdds')->name('user_adds');
Route::get('/condition/ads', 'HomeController@conditionAdds')->name('condition_adds');
Route::get('/price/range/ads', 'HomeController@priceRangeAdds')->name('price_range_adds');
Route::get('/search/ads', 'HomeController@searchAdds')->name('post_search');
Route::get('/help/support', 'HomeController@Support')->name('help_support');
Route::get('/about', 'HomeController@About')->name('about');

Route::prefix('users')->name('user.')->group(function(){
    Route::get('/userad','UserDetailsController@userAdd')->name('userdetails.useradd');
    Route::get('/save/favorite/{postid}','UserDetailsController@saveAsFavorite')->name('userdetails.save_as_favorite');
    Route::get('/favorite/ad','UserDetailsController@userFavorite')->name('userdetails.favoriteadd');
    Route::put('/change/password','UserDetailsController@changePassword')->name('userdetails.change_password');
    Route::get('/remove/favorite/{postid}','UserDetailsController@removeFavorite')->name('userdetails.removefavorite');

    Route::resource('/userdetails','UserDetailsController');


    Route::get('/ad/sold/{postid}','AddPostController@adSold')->name('userdetails.ad_sold');
    Route::resource('/addpost','AddPostController');

});




Route::namespace('Admin')->prefix('admin')->name('admin.')->group(function() {
    Route::resource('/roles','AdminRoleController',['except' => ['show']]);
    Route::resource('/users','AdminUserController',['except' => ['show']]);
    Route::resource('/categories','AdminCategoryController');
    Route::get('/category/ads/{id}','AdminCategoryController@categoryAd')->name('category.ads');

    Route::get('/dashboard','AdminController@index')->name('admin.dashboard');
    Route::get('/ad/featured/toggle/{id}','AdminController@featuredToggle')->name('admin.featured_toggle');
    Route::get('/ad/status/toggle/{id}','AdminController@statusToggle')->name('admin.status_toggle');
    Route::get('/admin/profile','AdminController@adminProfile')->name('admin.profile');
    Route::put('/admin/update/profile','AdminController@adminUpdateProfile')->name('admin.update.profile');
    Route::put('/admin/change/password','AdminController@adminChangePassword')->name('admin.change_password');
    Route::get('/all/adds','AdminController@allAds')->name('admin.all_ads');

});

resources/views/admin/partials/sidebar.blade.php
<!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{{ route('admin.admin.dashboard') }}">
        <div class="sidebar-brand-icon rotate-n-15">
          <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">AdZone</div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Dashboard -->
      <li class="nav-item">
        <a class="nav-link" href="{{ route('admin.admin.dashboard') }}">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Dashboard</span></a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">
        Interface
      </div>

      <!-- Nav Item - Pages Collapse Menu -->
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
          <i class="fas fa-users-cog"></i>
          <span>User Management</span>
        </a>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <a class="collapse-item" href="{{ route('admin.roles.create') }}">Add Role</a>
            <a class="collapse-item" href="{{ route('admin.roles.index') }}">All Roles</a>
            <a class="collapse-item" href="{{ route('admin.users.create') }}">Add Admin</a>
            <a class="collapse-item" href="{{ route('admin.users.index') }}">All User</a>
          </div>
        </div>
      </li>

      <hr class="sidebar-divider">

      <!-- Nav Item - Utilities Collapse Menu -->
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities" aria-expanded="true" aria-controls="collapseUtilities">
          <i class="fas fa-list-ol"></i>
          <span>AddZone</span>
        </a>
        <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <a class="collapse-item" href="{{ route('admin.categories.index') }}">Categories</a>
            <a class="collapse-item" href="{{ route('admin.admin.all_ads') }}">All Ads</a>
          </div>

        </div>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider">

    <!-- Nav Item - Pages Collapse Menu -->
      <li class="nav-item active">
        <a class="nav-link" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="true" aria-controls="collapsePages">
          <i class="fas fa-fw fa-user-md"></i>
          <span>Account</span>
        </a>
        <div id="collapsePages" class="collapse show" aria-labelledby="headingPages" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
             <a class="collapse-item" href="{{ route('admin.admin.profile') }}">Update Profile</a>

          </div>
        </div>
      </li>

      <hr class="sidebar-divider">



      <li class="nav-item">
            <a class="nav-link" href="{{ route('home') }}" target="_blank">
            <i class="fas fa-fw fa-home"></i>
            <span>View Site</span></a>
        </li>

      <!-- Divider -->
      <hr class="sidebar-divider d-none d-md-block">

      <!-- Sidebar Toggler (Sidebar) -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>

    </ul>

resources/views/admin/partials/topbar.blade.php
<nav class="navbar navbar-expand-md navbar-dark bg-dark shadow-sm">
                        <!-- Sidebar Toggle (Topbar) -->
                        <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                        </button>
                        <div class="container">
                            <a class="navbar-brand" href="{{ url('/') }}">
                            {{ config('app.name', 'Laravel') }}
                            </a>
                            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                            <span class="navbar-toggler-icon"></span>
                            </button>
                            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                                <!-- Left Side Of Navbar -->
                                <ul class="navbar-nav mr-auto">
                                </ul>
                                <!-- Right Side Of Navbar -->
                                <ul class="navbar-nav ml-auto">
                                    <!-- Authentication Links -->
                                    @guest
                                    <li class="nav-item">
                                        <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                    </li>
                                    @if (Route::has('register'))
                                    <li class="nav-item">
                                        <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                    </li>
                                    @endif
                                    @else
                                    <li class="nav-item dropdown no-arrow">
                                        <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                        {{ Auth::user()->name }} <span class="caret"></span>
                                        </a>
                                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                            <a class="dropdown-item" href="{{ route('admin.admin.profile') }}">
                                            <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i> Profile
                                            </a>
                                            <div class="dropdown-divider"></div>
                                            <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                                            <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i> Logout
                                            </a>
                                        </div>
                                    </li>
                                    @endguest
                                </ul>
                            </div>
                        </div>
                    </nav>